/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.MainFunctions;
import BackEnd.FileHandler;
import java.awt.Font;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class TrainFrame extends javax.swing.JFrame  {

    /**
     * Creates new form TrainFrame
     */
    public TrainFrame() {
        initComponents();
    }

    private List<List<Integer>> inputMatrix = new ArrayList<>();
    private List<List<Integer>> outputTemp = new ArrayList<>();
    private static String hiddenAF;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        learningRateTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxEpochsTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hiddenTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MSETF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hiddenAFCB = new javax.swing.JComboBox<>();
        accuracyJLabel = new javax.swing.JLabel();
        accuracy = new javax.swing.JLabel();
        trainBtn = new javax.swing.JButton();
        getDataFromFileBtn1 = new javax.swing.JButton();
        mainPageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Burbank Big Cd Bk", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Training");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 1, true));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter the Learning Rate");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        learningRateTF.setBackground(new java.awt.Color(204, 204, 204));
        learningRateTF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        learningRateTF.setForeground(new java.awt.Color(204, 0, 0));
        learningRateTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        learningRateTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        learningRateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningRateTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Max number of epochs");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        maxEpochsTF.setBackground(new java.awt.Color(204, 204, 204));
        maxEpochsTF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        maxEpochsTF.setForeground(new java.awt.Color(204, 0, 0));
        maxEpochsTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxEpochsTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        maxEpochsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxEpochsTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Number of neurons in Hidden Layer");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        hiddenTF.setBackground(new java.awt.Color(204, 204, 204));
        hiddenTF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        hiddenTF.setForeground(new java.awt.Color(204, 0, 0));
        hiddenTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hiddenTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        hiddenTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiddenTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MSE (Mean Squared Error)");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        MSETF.setBackground(new java.awt.Color(204, 204, 204));
        MSETF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        MSETF.setForeground(new java.awt.Color(204, 0, 0));
        MSETF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MSETF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        MSETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSETFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Select Activation Function For Hidden");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        hiddenAFCB.setBackground(new java.awt.Color(204, 0, 0));
        hiddenAFCB.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        hiddenAFCB.setForeground(new java.awt.Color(204, 204, 204));
        hiddenAFCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sigmoid", "Tanh", "RelU" }));
        hiddenAFCB.setAutoscrolls(true);
        hiddenAFCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        accuracyJLabel.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        accuracyJLabel.setForeground(new java.awt.Color(204, 204, 204));
        accuracyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accuracyJLabel.setText("Accuracy");
        accuracyJLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));

        accuracy.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        accuracy.setForeground(new java.awt.Color(204, 204, 204));
        accuracy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accuracyJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiddenAFCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 93, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(learningRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxEpochsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hiddenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MSETF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(learningRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxEpochsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hiddenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MSETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hiddenAFCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accuracyJLabel)
                    .addComponent(accuracy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        trainBtn.setBackground(new java.awt.Color(204, 204, 204));
        trainBtn.setFont(new java.awt.Font("Burbank Big Cd Bk", 0, 48)); // NOI18N
        trainBtn.setForeground(new java.awt.Color(204, 0, 0));
        trainBtn.setText("Train");
        trainBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        trainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainBtnActionPerformed(evt);
            }
        });

        getDataFromFileBtn1.setBackground(new java.awt.Color(255, 0, 0));
        getDataFromFileBtn1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        getDataFromFileBtn1.setForeground(new java.awt.Color(204, 204, 204));
        getDataFromFileBtn1.setText("Get The Data From File");
        getDataFromFileBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDataFromFileBtn1ActionPerformed(evt);
            }
        });

        mainPageBtn.setBackground(new java.awt.Color(255, 0, 0));
        mainPageBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        mainPageBtn.setForeground(new java.awt.Color(204, 204, 204));
        mainPageBtn.setText("Main Page");
        mainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(trainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(getDataFromFileBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mainPageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(trainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(191, Short.MAX_VALUE)
                    .addComponent(getDataFromFileBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(184, 184, 184)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learningRateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningRateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_learningRateTFActionPerformed

    private void maxEpochsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxEpochsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxEpochsTFActionPerformed

    private void hiddenTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiddenTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenTFActionPerformed

    private void MSETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MSETFActionPerformed

    private void trainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainBtnActionPerformed

        List <List<Double>> outputMatrix = FileHandler.convertIntToDouble(outputTemp);
        Double accuracy = 0.0;
        setHiddenAF(hiddenAFCB.getSelectedItem().toString());
        try {
          accuracy =  MainFunctions.Train(Double.parseDouble(learningRateTF.getText()),
                    Integer.parseInt(maxEpochsTF.getText()),
                    Integer.parseInt(hiddenTF.getText()),
                    Double.parseDouble(MSETF.getText()),
                    hiddenAFCB.getSelectedItem().toString(),
                    inputMatrix,
                    outputMatrix);
        } catch (IOException ex) {
            Logger.getLogger(TrainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        JLabel label = new JLabel("Your system is trained, give it a shot!");
        Font customFont = new Font("Arial", Font.BOLD, 17); // Replace "Arial" with your desired font
        label.setFont(customFont);       
        JOptionPane.showMessageDialog(null, label,"System Update",JOptionPane.INFORMATION_MESSAGE);
        
        accuracy *= 100;
        
        
        String accuracyString = String.format("%." + 2 + "f", accuracy);
        
        this.accuracy.setText(accuracyString + "%");

    }//GEN-LAST:event_trainBtnActionPerformed

    private void getDataFromFileBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDataFromFileBtn1ActionPerformed
        
        try {
            inputMatrix = FileHandler.getInputLists(FileHandler.readMatrix());
            outputTemp = FileHandler.getOutputLists(FileHandler.readMatrix());
        } catch (IOException ex) {
             Logger.getLogger(TrainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JLabel label = new JLabel("Your training set is ready, go ahead and train it.");
        Font customFont = new Font("Arial", Font.BOLD, 17); // Replace "Arial" with your desired font
        label.setFont(customFont); 
        JOptionPane.showMessageDialog(null, label,"System Update",JOptionPane.INFORMATION_MESSAGE);
       
        
        
    }//GEN-LAST:event_getDataFromFileBtn1ActionPerformed

    public static String getHiddenAF(){ return hiddenAF;}
    
    
    
    public void setHiddenAF(String hiddenAF){
        this.hiddenAF = hiddenAF;
        
    }
    
    
    
    private void mainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageBtnActionPerformed
        
         MainFrame main = new MainFrame();
         main.setLocationRelativeTo(null);
         main.show();
         dispose();
    }//GEN-LAST:event_mainPageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MSETF;
    private javax.swing.JLabel accuracy;
    private javax.swing.JLabel accuracyJLabel;
    private javax.swing.JButton getDataFromFileBtn1;
    private javax.swing.JComboBox<String> hiddenAFCB;
    private javax.swing.JTextField hiddenTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField learningRateTF;
    private javax.swing.JButton mainPageBtn;
    private javax.swing.JTextField maxEpochsTF;
    private javax.swing.JButton trainBtn;
    // End of variables declaration//GEN-END:variables
}
